# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

runsimplexRegression <- function(A, B) {
    .Call(`_ACTIONcore_runsimplexRegression`, A, B)
}

runSPA <- function(A, k) {
    .Call(`_ACTIONcore_runSPA`, A, k)
}

runAA <- function(A, W0) {
    .Call(`_ACTIONcore_runAA`, A, W0)
}

runACTION <- function(cell_signatures, k_min, k_max, numThreads) {
    .Call(`_ACTIONcore_runACTION`, cell_signatures, k_min, k_max, numThreads)
}

