// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include "../inst/include/ACTIONcore.h"
#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// runsimplexRegression
mat runsimplexRegression(mat A, mat B);
RcppExport SEXP _ACTIONcore_runsimplexRegression(SEXP ASEXP, SEXP BSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< mat >::type A(ASEXP);
    Rcpp::traits::input_parameter< mat >::type B(BSEXP);
    rcpp_result_gen = Rcpp::wrap(runsimplexRegression(A, B));
    return rcpp_result_gen;
END_RCPP
}
// runSPA
mat runSPA(mat A, int k);
RcppExport SEXP _ACTIONcore_runSPA(SEXP ASEXP, SEXP kSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< mat >::type A(ASEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    rcpp_result_gen = Rcpp::wrap(runSPA(A, k));
    return rcpp_result_gen;
END_RCPP
}
// runAA
List runAA(mat A, mat W0);
RcppExport SEXP _ACTIONcore_runAA(SEXP ASEXP, SEXP W0SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< mat >::type A(ASEXP);
    Rcpp::traits::input_parameter< mat >::type W0(W0SEXP);
    rcpp_result_gen = Rcpp::wrap(runAA(A, W0));
    return rcpp_result_gen;
END_RCPP
}
// runACTION
List runACTION(mat cell_signatures, int k_min, int k_max, int numThreads);
RcppExport SEXP _ACTIONcore_runACTION(SEXP cell_signaturesSEXP, SEXP k_minSEXP, SEXP k_maxSEXP, SEXP numThreadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< mat >::type cell_signatures(cell_signaturesSEXP);
    Rcpp::traits::input_parameter< int >::type k_min(k_minSEXP);
    Rcpp::traits::input_parameter< int >::type k_max(k_maxSEXP);
    Rcpp::traits::input_parameter< int >::type numThreads(numThreadsSEXP);
    rcpp_result_gen = Rcpp::wrap(runACTION(cell_signatures, k_min, k_max, numThreads));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_ACTIONcore_runsimplexRegression", (DL_FUNC) &_ACTIONcore_runsimplexRegression, 2},
    {"_ACTIONcore_runSPA", (DL_FUNC) &_ACTIONcore_runSPA, 2},
    {"_ACTIONcore_runAA", (DL_FUNC) &_ACTIONcore_runAA, 2},
    {"_ACTIONcore_runACTION", (DL_FUNC) &_ACTIONcore_runACTION, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_ACTIONcore(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
