---
title: "Demo of ACTION run"
output: html_notebook
---

## Import expression matrix
```{r message=FALSE, warning=FALSE}
require(Matrix)

input_path = '../../../datasets/MouseBrain/RNA/';
fname = paste(input_path, 'preprocessed.RDS', sep='/')
if(!file.exists(fname)) {
  expression = readMM(paste(input_path, 'expression.mm', sep='/'));
  gene_names = read.table(paste(input_path, 'gene_names.txt', sep='/'), as.is = T)$V1
  sample_annotations = read.table(paste(input_path, 'sample_annotations.txt', sep='/'), header = T)
  RNASeq = list(expression = expression, gene_names = gene_names, sample_annotations = sample_annotations)
  saveRDS(RNASeq, fname)
} else {
  RNASeq = readRDS(fname)
}

Labels = as.character(RNASeq$sample_annotations$Labels)
UL = sort(unique(Labels))
labels = match(Labels, UL)
```

## Run ACTION
```{r message=FALSE, warning=FALSE}
require(Matrix)
require(ACTION)

reduction.out = reduceGeneExpression(RNASeq$expression, reduced_dim = 30, method = 1)
S_r = reduction.out$S_r

k_min = 2
k_max = 15
ACTION.results = runACTION(S_r, k_min = k_min, k_max = k_max, numThreads = 8)

C_trace = ACTION.results$C
H_trace = ACTION.results$H
```

## Discretize results and evaluate clusters
```{r message=FALSE, warning=FALSE}
require(ClusterR)

ARI = array(0, dim = c(k_max, 1))
NMI = array(0, dim = c(k_max, 1))
for(k in k_min:k_max) {
  H = H_trace[[k]]
  predicted_celltype = apply(H, 2, which.max)
  ARI[k] = external_validation(labels, predicted_celltype, method = "adjusted_rand_index")
  NMI[k] = external_validation(labels, predicted_celltype, method = "nmi")
}

plot(k_min:k_max, ARI[k_min:k_max], xlab = '# archs', ylab = 'ARI')
plot(k_min:k_max, NMI[k_min:k_max], xlab = '# archs', ylab = 'NMI')

```


